// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lugjdhumfachxplinsmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1Z2pkaHVtZmFjaHhwbGluc21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzIwODMsImV4cCI6MjA2OTYwODA4M30.nvD8upAiVAZaLJECUUZj6mVyje3ip7JZ2lvc3d3lyWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});